source 'https://rubygems.org'

gem 'mimi', '~> <%= Mimi::VERSION.sub(/\.\d+$/,'') %>'

# Uncomment these lines to use mimi-db or mimi-messaging:
#
# gem 'mimi/db', '~> 0.1'
# gem 'mimi/messaging', '~> 0.1'

group :development do
  gem 'rake', '~> 10.5'
  gem 'pry', '~> 0.10'
  gem 'rspec', '~> 3.4'
end
